### ISSUE TITLE
Wifi was disabled after installation

### ISSUE THREAD

**Issue by diegoveloper** [ppkantorski/Airplane-Sleep#1]
I'm using my macbook in clamshell mode, so after install this app the WIFI was turned off, any way to avoid disabling WIFI when macbook is in clamshell mode.

**Comment by ppkantorski** [comment]
hey sorry for the late response.. ill have to think about it.  a quick but less ideal workaround is to just enable wifi when clamshell mode is activated.  maybe I can add something that can tell if your computer has sleep disabled and if so, don't disable wifi and Bluetooth.  in general, for me, when I am in clamshell mode I use a USB ethernet adapter so I haven't encountered this issue.

**Comment by diegoveloper** [comment]
Oh, well I couldn't reproduce the issue anymore. I'll close this issue. Thanks :).
